In [1]:
import numpy as np

In [2]:
hitung = np.arange(20).reshape(4, 5)
hitung

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [3]:
a = np.linspace(2.0, 3.0, num=20).reshape(4, 5)

In [4]:
a

array([[2.        , 2.05263158, 2.10526316, 2.15789474, 2.21052632],
       [2.26315789, 2.31578947, 2.36842105, 2.42105263, 2.47368421],
       [2.52631579, 2.57894737, 2.63157895, 2.68421053, 2.73684211],
       [2.78947368, 2.84210526, 2.89473684, 2.94736842, 3.        ]])

In [5]:
hitung[3, :]

array([15, 16, 17, 18, 19])

# Numpy 3D

In [6]:
arr = np.array([[[3, 1, 12], [19, 11, 11]], [[21, 59, 13], [1, 5, 0]], [[41, 6, 19], [15, 21, 19]]])
arr

array([[[ 3,  1, 12],
        [19, 11, 11]],

       [[21, 59, 13],
        [ 1,  5,  0]],

       [[41,  6, 19],
        [15, 21, 19]]])

In [7]:
arr.shape

(3, 2, 3)

In [8]:
arr[:, 1, 0]

array([19,  1, 15])

In [9]:
iden = np.identity(9, dtype="int32")
iden

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int32)

In [10]:
arr = np.array([[1, 2, 3]])
np.repeat(arr, 3).reshape(-1, 1)

array([[1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [3],
       [3],
       [3]])

In [11]:
np.repeat(arr, 3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [12]:
kosong = np.ones((3,3), dtype="int32")
kosong[1, 1] = 100
kosong

array([[  1,   1,   1],
       [  1, 100,   1],
       [  1,   1,   1]], dtype=int32)

In [13]:
def sps():
    print()

print(iden)
print("")
iden[6:, 1:-5] = kosong
print(iden)
sps()
b = np.full((3, 3), 9)
print(b)
sps()
iden[0:3, 5:-1] = b
iden

[[1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1]]

[[  1   0   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0   0]
 [  0   0   1   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   0   0]
 [  0   0   0   0   1   0   0   0   0]
 [  0   0   0   0   0   1   0   0   0]
 [  0   1   1   1   0   0   1   0   0]
 [  0   1 100   1   0   0   0   1   0]
 [  0   1   1   1   0   0   0   0   1]]

[[9 9 9]
 [9 9 9]
 [9 9 9]]



array([[  1,   0,   0,   0,   0,   9,   9,   9,   0],
       [  0,   1,   0,   0,   0,   9,   9,   9,   0],
       [  0,   0,   1,   0,   0,   9,   9,   9,   0],
       [  0,   0,   0,   1,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   1,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   1,   0,   0,   0],
       [  0,   1,   1,   1,   0,   0,   1,   0,   0],
       [  0,   1, 100,   1,   0,   0,   0,   1,   0],
       [  0,   1,   1,   1,   0,   0,   0,   0,   1]], dtype=int32)

In [14]:
print(kosong)
print("Memiliki dimensi", kosong.shape)
print(b)
print("Memiliki dimensi", b.shape)
np.matmul(kosong, b)

[[  1   1   1]
 [  1 100   1]
 [  1   1   1]]
Memiliki dimensi (3, 3)
[[9 9 9]
 [9 9 9]
 [9 9 9]]
Memiliki dimensi (3, 3)


array([[ 27,  27,  27],
       [918, 918, 918],
       [ 27,  27,  27]])

In [15]:
stats = np.array([[1, -2, 2], [4, -1, 0], [0, -3, 5]])
stats

array([[ 1, -2,  2],
       [ 4, -1,  0],
       [ 0, -3,  5]])

In [16]:
print(np.min(stats, axis=0))
print(np.min(stats, axis=1))
sps()
print(np.max(stats, axis=0))
print(np.max(stats, axis=0))

[ 0 -3  0]
[-2 -1 -3]

[ 4 -1  5]
[ 4 -1  5]


In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 22, 0, 44])
hasil = np.vstack([a, b])
hasil

array([[ 1,  2,  3,  4],
       [10, 22,  0, 44]])

In [18]:
x, y = np.vsplit(hasil, 2)
print(x)
sps()
print(y)

[[1 2 3 4]]

[[10 22  0 44]]


In [19]:
h_array = hasil[hasil > 3]
h_array

array([ 4, 10, 22, 44])

In [20]:
print(iden)
sps()
print(iden[[0, 1, 2, 3, 4, 5, 6, 7, 8], [0, 1, 2, 3, 4, 5, 6, 7, 8]])
sps()
print(iden[[8, 7, 6, 5, 4, 3, 2 ,1], [1, 2, 3, 4, 5, 6, 7, 8]])
iden[2:, [1, 2, 4, 7]]

[[  1   0   0   0   0   9   9   9   0]
 [  0   1   0   0   0   9   9   9   0]
 [  0   0   1   0   0   9   9   9   0]
 [  0   0   0   1   0   0   0   0   0]
 [  0   0   0   0   1   0   0   0   0]
 [  0   0   0   0   0   1   0   0   0]
 [  0   1   1   1   0   0   1   0   0]
 [  0   1 100   1   0   0   0   1   0]
 [  0   1   1   1   0   0   0   0   1]]

[1 1 1 1 1 1 1 1 1]

[  1 100   1   0   0   0   9   0]


array([[  0,   1,   0,   9],
       [  0,   0,   0,   0],
       [  0,   0,   1,   0],
       [  0,   0,   0,   0],
       [  1,   1,   0,   0],
       [  1, 100,   0,   1],
       [  1,   1,   0,   0]], dtype=int32)

# PENGGUNAAN LAMBDA

In [21]:
def hitung(x): #Contoh Misal dengan funsi
    if x > 3:
        x *= 3
        return x
    else:
        return x

list1 = [2, 4, 5, 6]
list2 = list(map(hitung, list1))
print(list2)

list3 = list(map(lambda x:x*2, list1))
list4 = list3
print(list3)
type(list3)

list4 = np.array(list4)
type(list4)

[2, 12, 15, 18]
[4, 8, 10, 12]


numpy.ndarray

/tmp/ipykernel_9769/4281911692.py:1: RuntimeWarning: divide by zero encountered in log
  1 - np.log(0)


inf