In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score
from sklearn.metrics import precision_recall_curve
from sklearn.model_selection import cross_val_predict
from sklearn.linear_model import SGDClassifier
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

2022-09-11 00:47:41.543843: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-09-11 00:47:41.611235: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-09-11 00:47:41.611262: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
data = pd.read_csv("datasets/spam_or_not_spam.csv")
data

email  label
0      date wed NUMBER aug NUMBER NUMBER NUMBER NUMB...      0
1     martin a posted tassos papadopoulos the greek ...      0
2     man threatens explosion in moscow thursday aug...      0
3     klez the virus that won t die already the most...      0
4      in adding cream to spaghetti carbonara which ...      0
...                                                 ...    ...
2995   abc s good morning america ranks it the NUMBE...      1
2996   hyperlink hyperlink hyperlink let mortgage le...      1
2997   thank you for shopping with us gifts for all ...      1
2998   the famous ebay marketing e course learn to s...      1
2999   hello this is chinese traditional 子 件 NUMBER世...      1

[3000 rows x 2 columns]

In [3]:
data.dropna(inplace=True)

In [4]:
X = data["email"].values
y = data["label"].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [5]:
tokenizer = Tokenizer(num_words=250, oov_token="x")
tokenizer.fit_on_texts(X_train)

kalimat_train = tokenizer.texts_to_sequences(X_train)
kalimat_test = tokenizer.texts_to_sequences(X_test)

pading_train = pad_sequences(kalimat_train)
pading_test = pad_sequences(kalimat_test)

In [6]:
model = Sequential([
    layers.Embedding(250, 16),
    layers.GlobalAveragePooling1D(),
    layers.Dense(64, activation="relu"),
    layers.Dropout(0.3),
    layers.Dense(64, activation="relu"),
    layers.Dropout(0.3),
    layers.Dense(1, activation="sigmoid")
])

2022-09-11 00:47:44.593492: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-09-11 00:47:44.593518: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-09-11 00:47:44.593533: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (parrot-swiftsf31459): /proc/driver/nvidia/version does not exist
2022-09-11 00:47:44.593706: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [7]:
model.compile(
    loss="binary_crossentropy",
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    metrics=["accuracy"]
)

In [8]:
history = model.fit(pading_train, y_train, 
                    validation_data=(pading_test, y_test), 
                    epochs=40, verbose=2)

Epoch 1/40
75/75 - 2s - loss: 0.5329 - accuracy: 0.8370 - val_loss: 0.4720 - val_accuracy: 0.8200 - 2s/epoch - 21ms/step
Epoch 2/40
75/75 - 1s - loss: 0.4527 - accuracy: 0.8370 - val_loss: 0.4713 - val_accuracy: 0.8200 - 1s/epoch - 14ms/step
Epoch 3/40
75/75 - 1s - loss: 0.4498 - accuracy: 0.8370 - val_loss: 0.4698 - val_accuracy: 0.8200 - 1s/epoch - 16ms/step
Epoch 4/40
75/75 - 1s - loss: 0.4524 - accuracy: 0.8370 - val_loss: 0.4688 - val_accuracy: 0.8200 - 1s/epoch - 15ms/step
Epoch 5/40
75/75 - 1s - loss: 0.4471 - accuracy: 0.8370 - val_loss: 0.4694 - val_accuracy: 0.8200 - 1s/epoch - 15ms/step
Epoch 6/40
75/75 - 1s - loss: 0.4435 - accuracy: 0.8370 - val_loss: 0.4677 - val_accuracy: 0.8200 - 1s/epoch - 15ms/step
Epoch 7/40
75/75 - 1s - loss: 0.4505 - accuracy: 0.8370 - val_loss: 0.4670 - val_accuracy: 0.8200 - 1s/epoch - 14ms/step
Epoch 8/40
75/75 - 1s - loss: 0.4464 - accuracy: 0.8370 - val_loss: 0.4664 - val_accuracy: 0.8200 - 1s/epoch - 14ms/step
Epoch 9/40
75/75 - 1s - loss: 0.

In [17]:
y_pred = model.predict(pading_test)

y_pred = np.round(y_pred)
y_pred

19/19 [==============================] - 0s 2ms/step


array([[0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [18]:
confusion_matrix(y_test, y_pred)

array([[479,  13],
       [  5, 103]])

In [21]:
print(f"Preccision : {precision_score(y_test, y_pred)}\nRecall : {recall_score(y_test, y_pred)}")

Preccision : 0.8879310344827587
Recall : 0.9537037037037037


In [32]:
pading_train.shape, y_train.shape

((2399, 13303), (2399,))

In [33]:
y_scores = cross_val_predict(model, pading_train, y_train, cv=3, method="decision_function")

TypeError: Cannot clone object '<keras.engine.sequential.Sequential object at 0x7f5b63e25100>' (type <class 'keras.engine.sequential.Sequential'>): it does not seem to be a scikit-learn estimator as it does not implement a 'get_params' method.

In [20]:
batas = 400

hasil = (y_score < batas) # Pake Operator > atau <
hasil

NameError: name 'y_score' is not defined

In [319]:
y_batas = (y_score < 50) # Atur batas Prec / Recall
# y_test.shape # 600 baris
print(f"Preccision : {precision_score(y_test, y_batas)}\nRecall : {recall_score(y_test, y_batas)}")

Preccision : 0.1618705035971223
Recall : 0.9574468085106383


In [321]:
confusion_matrix(y_test, y_batas)

array([[ 40, 466],
       [  4,  90]])

19/19 [==============================] - 0s 2ms/step


array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1.,
        0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 

In [276]:
data[(data["label"] == 0)].iloc[10:31]

email  label
10  hello have you seen and discussed this article...      0
11  yes great minds think alike but even withput e...      0
12  on mon aug NUMBER NUMBER at NUMBER NUMBER NUMB...      0
13   from chris garrigues cwg exmh deepeddy com da...      0
14  spamassassin is hurting democracy owen URL int...      0
15  hi all apologies for the possible silly questi...      0
16   in forteana y d mcmann dmcmann b wrote robert...      0
17  in a nutshell solaris is suns own flavour of u...      0
18  apols if this has been posted before URL rob y...      0
19  can someone explain what type of operating sys...      0
20   apols if this has been posted before URL so a...      0
21  on thu aug NUMBER NUMBER at NUMBER NUMBER NUMB...      0
22  john p looney wrote on thu aug NUMBER NUMBER a...      0
23  hey it s not easy being green leslie leslie el...      0
24   on thu NUMBER aug NUMBER john p looney wrote ...      0
25   you have multiple generations of peasants squ...      0
26  folks my first time posting have a bit of unix...      0
27  on thu NUMBER aug NUMBER joseph s barrera iii ...      0
28  joseph s barrera iii wrote chris haun wrote a ...      0
29  update on this for anyone that s interested an...      0
30  has anyone seen heard of used some package tha...      0