In [2]:
import pandas as pd
import tensorflow as tf
import numpy as np
import sklearn.preprocessing as pre
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from warnings import filterwarnings
filterwarnings("ignore")

In [3]:
data = pd.read_csv('citrus.csv')
data

name  diameter  weight  red  green  blue
0         orange      2.96   86.76  172     85     2
1         orange      3.91   88.05  166     78     3
2         orange      4.42   95.17  156     81     2
3         orange      4.47   95.60  163     81     4
4         orange      4.48   95.76  161     72     9
...          ...       ...     ...  ...    ...   ...
9995  grapefruit     15.35  253.89  149     77    20
9996  grapefruit     15.41  254.67  148     68     7
9997  grapefruit     15.59  256.50  168     82    20
9998  grapefruit     15.92  260.14  142     72    11
9999  grapefruit     16.45  261.51  152     74     2

[10000 rows x 6 columns]

In [3]:
name = pre.LabelEncoder()
name.fit(data["name"])
data["name"] = name.transform(data["name"])

# Ubah type data
data["name"] = data["name"].astype("float32")
data

name  diameter  weight  red  green  blue
0      1.0      2.96   86.76  172     85     2
1      1.0      3.91   88.05  166     78     3
2      1.0      4.42   95.17  156     81     2
3      1.0      4.47   95.60  163     81     4
4      1.0      4.48   95.76  161     72     9
...    ...       ...     ...  ...    ...   ...
9995   0.0     15.35  253.89  149     77    20
9996   0.0     15.41  254.67  148     68     7
9997   0.0     15.59  256.50  168     82    20
9998   0.0     15.92  260.14  142     72    11
9999   0.0     16.45  261.51  152     74     2

[10000 rows x 6 columns]

# UBAH MENJADI ARRAY

In [4]:
dataset = data.values

# MELAKUKAN NORMALISASI DATA

In [5]:
X = dataset[:, 1:]
y = dataset[:, 0]

skala = pre.MinMaxScaler()
X = skala.fit_transform(X)
X

array([[0.        , 0.        , 0.74025974, 0.63529412, 0.        ],
       [0.07042254, 0.00738197, 0.66233766, 0.55294118, 0.01851852],
       [0.10822832, 0.04812589, 0.53246753, 0.58823529, 0.        ],
       ...,
       [0.93624907, 0.97133047, 0.68831169, 0.6       , 0.33333333],
       [0.96071164, 0.99216023, 0.35064935, 0.48235294, 0.16666667],
       [1.        , 1.        , 0.48051948, 0.50588235, 0.        ]])

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# MEMBUAT 3 LAYERS

In [7]:
# Pada input shape diberikan 5 karena kita memiliki 5 Features
# Pada activation function pilih sigmoid karena probabilitas 0 dan 1 Cocok untuk klasifikasi biner
model = Sequential([    
                    Dense(32, activation='relu', input_shape=(5,)),    
                    Dense(32, activation='relu'),    
                    Dense(1, activation='sigmoid')
])

2022-06-26 20:37:45.649417: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-06-26 20:37:45.649440: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-06-26 20:37:45.649453: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (parrot-swiftsf31459): /proc/driver/nvidia/version does not exist
2022-06-26 20:37:45.649624: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


# MEMBUAT COMPILE

In [8]:
# Pada optimizer pilih "sgd", karena cocok untuk dataset berukuran kecil
model.compile(optimizer='sgd', 
              loss='binary_crossentropy', 
              metrics=['accuracy'])

In [9]:
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
219/219 [==============================] - 0s 650us/step - loss: 0.6765 - accuracy: 0.5594
Epoch 2/100
219/219 [==============================] - 0s 636us/step - loss: 0.6220 - accuracy: 0.8584
Epoch 3/100
219/219 [==============================] - 0s 617us/step - loss: 0.5593 - accuracy: 0.9086
Epoch 4/100
219/219 [==============================] - 0s 606us/step - loss: 0.4773 - accuracy: 0.9127
Epoch 5/100
219/219 [==============================] - 0s 616us/step - loss: 0.3883 - accuracy: 0.9224
Epoch 6/100
219/219 [==============================] - 0s 598us/step - loss: 0.3141 - accuracy: 0.9257
Epoch 7/100
219/219 [==============================] - 0s 622us/step - loss: 0.2640 - accuracy: 0.9254
Epoch 8/100
219/219 [==============================] - 0s 610us/step - loss: 0.2331 - accuracy: 0.9249
Epoch 9/100
219/219 [==============================] - 0s 600us/step - loss: 0.2147 - accuracy: 0.9249
Epoch 10/100
219/219 [==============================] - 0s 625us/step - l

# MENGEVALUASI MODEL

In [10]:
# Elemen pertama  loss, Elemen kedua akurasi
model.evaluate(X_test, y_test)

94/94 [==============================] - 0s 609us/step - loss: 0.1694 - accuracy: 0.9340


[0.16937905550003052, 0.9340000152587891]

In [11]:
# z = np.array([15.35, 253.89, 149, 77, 20]).reshape(1,-1)
# y_pred = model.predict(z)
y_pred = model.predict(X_test[:20])

# Membuat bil Int dari Dec
bulat = np.round(y_pred).reshape(1,-1)
y_pred = np.round(bulat)
y_pred

1/1 [==============================] - 0s 45ms/step


array([[0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
        0., 1., 1., 0.]], dtype=float32)

In [12]:
a = y_pred.flatten()
b = y_test[:20].flatten()

data = {
    "y_test" : b,
    "y_pred" : a
}
pd.DataFrame(data)

y_test  y_pred
0      0.0     0.0
1      0.0     0.0
2      0.0     1.0
3      1.0     1.0
4      1.0     1.0
5      0.0     0.0
6      0.0     0.0
7      0.0     0.0
8      1.0     1.0
9      1.0     1.0
10     0.0     0.0
11     1.0     1.0
12     1.0     1.0
13     1.0     1.0
14     1.0     1.0
15     1.0     1.0
16     0.0     0.0
17     1.0     1.0
18     1.0     1.0
19     0.0     0.0

In [13]:
X_test

array([[0.5767235 , 0.56526466, 0.49350649, 0.29411765, 0.2962963 ],
       [0.8250556 , 0.86981402, 0.48051948, 0.55294118, 0.75925926],
       [0.55151964, 0.53436338, 0.45454545, 0.55294118, 0.        ],
       ...,
       [0.56115641, 0.54638054, 0.55844156, 0.50588235, 0.22222222],
       [0.79466271, 0.8297568 , 0.32467532, 0.45882353, 0.11111111],
       [0.34247591, 0.29991416, 0.41558442, 0.49411765, 0.        ]])